version: '3'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: DontUseThisPasswordOnProduction
      MONGO_INITDB_DATABASE: mango
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: DontUseThisPasswordOnProduction
      ME_CONFIG_MONGODB_URL: mongodb://dev:DontUseThisPasswordOnProduction@mongodb:27017/
      ME_CONFIG_BASICAUTH: false

  server:
    build:
      context: ../server/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../server:/app